from pathlib import Path
from typing import Literal

from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

# Resolve backend/.env regardless of CWD (uvicorn, pytest, etc.)
_BACKEND_DIR = Path(__file__).resolve().parents[2]
_ENV_FILE = _BACKEND_DIR / ".env"


class Settings(BaseSettings):
    app_name: str = "Cost-Aware Multi-Model Router"
    app_version: str = "1.0.0"
    debug: bool = True
    environment: str = "development"

    mistral_api_key: str | None = None
    gemini_api_key: str | None = None
    xai_api_key: str | None = None
    groq_api_key: str | None = None
    deepseek_api_key: str | None = None

    langchain_tracing_v2: bool = True
    langchain_api_key: str | None = None
    langchain_project: str = "cost-aware-router"

    confidence_threshold: float = Field(default=0.75, ge=0.0, le=1.0)

    # Phase 3 classifier: FIXED strongest model (accuracy first).
    # NOTE: cost-aware selection is Phase 4 — do NOT pick this dynamically.
    # LANGCHAIN_API_KEY is the LangSmith tracing key only; it is never
    # used for inference and never interchanged with provider keys above.
    classifier_model: str = "mistral-large-latest"
    classifier_provider: str = "mistral"
    classifier_timeout_s: float = Field(default=20.0, gt=0.0)
    max_prompt_chars: int = Field(default=4000, gt=0)

    # Phase 5 execution service: generic inference calls (answer flow).
    # Separate from the classifier's budget on purpose.
    execution_timeout_s: float = Field(default=30.0, gt=0.0)
    execution_max_tokens: int = Field(default=1024, gt=0)

    # Phase 7 reliability: same-provider retries + capable-provider
    # failover inside the execution service. Transport errors only —
    # never answer content (quality stays Phase 6's job).
    reliability_max_retries: int = Field(default=2, ge=0)
    reliability_backoff_base_s: float = Field(default=0.5, ge=0.0)

    # Phase 6 quality judge: FIXED strongest model (accuracy first),
    # like the classifier. quality_pass_threshold is ANSWER quality and
    # must never be confused with confidence_threshold (classification).
    judge_model: str = "mistral-large-latest"
    judge_provider: str = "mistral"
    quality_pass_threshold: float = Field(default=0.7, ge=0.0, le=1.0)

    # Phase 10 Clerk auth: public, non-secret endpoint config. The .env
    # already carries Clerk secret keys, but those alone are NOT enough —
    # the JWKS URL and issuer below must be configured by the operator.
    # Empty values fail closed (every token → 401), never open.
    clerk_jwks_url: str = ""
    clerk_issuer: str = ""
    clerk_jwks_cache_ttl_s: float = Field(default=600.0, gt=0.0)

    # Browser dashboard support: origins allowed by CORS (dev defaults
    # cover localhost/127.0.0.1 on the usual Next.js ports — the UI may
    # run on :3000 or :3001, and both spellings of localhost occur).
    frontend_origins: list[str] = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3001",
    ]

    # Observability: stdout log verbosity (LOG_LEVEL env overrides).
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR"] = "INFO"

    # Backend token sessions: HS256 self-minted access + refresh tokens.
    # jwt_secret_key is REQUIRED (fail closed when empty) and must be
    # generated by the operator, e.g. secrets.token_urlsafe(48).
    # Never commit it; .env only.
    jwt_secret_key: str = ""
    jwt_access_minutes: int = Field(default=15, gt=0)
    jwt_refresh_days: int = Field(default=7, gt=0)
    refresh_cookie_name: str = "rt"

    # Phase 11 MongoDB & Persistence Settings (names match backend/.env).
    mongodb_uri: str = "mongodb://localhost:27017"
    mongodb_database: str = "cost_aware_router"

    # Privacy Controls for Query Persistence
    privacy_store_prompts: bool = True
    privacy_store_answers: bool = True
    privacy_store_execution_trace: bool = True
    privacy_anonymize_user: bool = False

    model_config = SettingsConfigDict(
        env_file=str(_ENV_FILE),
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    @model_validator(mode="after")
    def validate_classifier_model(self) -> "Settings":
        provider = self.classifier_provider.lower()
        model = self.classifier_model.lower()
        if provider == "gemini" and "gemini" not in model:
            raise ValueError(f"Model {self.classifier_model} is not compatible with provider gemini")
        if provider == "mistral" and "mistral" not in model and "mixtral" not in model:
            raise ValueError(f"Model {self.classifier_model} is not compatible with provider mistral")
        return self


settings = Settings()